# Generated by Django 2.2.4 on 2019-09-17 22:50

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=300)),
                ('published_date', models.DateField(default=datetime.date(2019, 9, 17))),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('detail', models.CharField(max_length=1000)),
            ],
        ),
    ]
