# Generated by Django 2.2.4 on 2019-09-22 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='published_date',
            field=models.DateField(default=datetime.date(2019, 9, 22)),
        ),
    ]
