# Generated by Django 2.2.4 on 2019-09-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190924_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
