# Generated by Django 2.2.4 on 2019-09-24 03:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_event_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
