# Generated by Django 2.2.4 on 2019-09-25 01:43

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_heritage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritage',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heritage',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='heritage',
            name='open_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Sunday', max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heritage',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='published_date',
            field=models.DateField(default=datetime.date(2019, 9, 25)),
        ),
    ]
