# Generated by Django 2.2.4 on 2019-09-30 12:44

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190925_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritage',
            name='open_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='published_date',
            field=models.DateField(default=datetime.date(2019, 9, 30)),
        ),
    ]
