# Generated by Django 2.2.4 on 2019-09-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=100),
        ),
    ]
